version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tedivm/gitstars
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest . | cat

  publish-latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Setup Environment
        command: |
          echo 'export VERSION_TAG=$(date -u +%y%m%d%H%M)"' >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest . | cat
            docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG . | cat
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest | cat
            docker push $IMAGE_NAME:$VERSION_TAG | cat

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  publish:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: master
